sonar.projectKey=anisul-islam-prog_assignment-15
sonar.organization=anisul-islam-prog
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.14
sonar.exclusions=terraform/**,.github/**,tests/**